### ISSUE TITLE
Will it possible to reword to intro swc / esbuild bit?

### ISSUE THREAD

**Issue by kwonoj** [vitejs/vite-plugin-react-swc#10]
Hi! I am core SWC team member, maintaining SWC with @kdy1's development lead.

First, congrats and exciting to see now SWC is supported toolchain for the Vite. I wanted to have this for long time.

Meanwhile, if you don't mind I would like to ask small favor to introduce SWC and esbuild -

> Use the versatility of SWC for development and the maturity of esbuild for production

I am a non-native English speaker so I may read things as not the way native speakers read, but for me this read as a comparison that SWC is versatile, not mature for prod yet, esbuild is mature for prod, not versatile yet. Given SWC is widely used for the production application / framework (next.js, deno, and other private codebases I can't share publicly) and esbuild is widely used for various toolchain, I hope this could be reworded bit for the clarity. This would be helpful for the non-native readers like me won't have those impressions.

Thanks, and congrats again for the launch.

**Comment by ArnaudBarre** [comment]
Thanks for the feedback.

When I started this plugin almost one year ago, I felt like esbuild was more mature for production because the bundling/minification part felt more stable. Maybe I was wrong, I see that next 12 is older than that.

I know that today this is not true at all for minification. I will find another tagline that doesn't suggest that SWC is not production ready before the next release

**Comment by kwonoj** [comment]
Thanks! appreciate for the quick response. Really excited to see SWC works with Vite.
