### ISSUE TITLE
`TypeError: react is not a function` when importing via commonjs

### ISSUE THREAD

**Issue by benatshippabo** [vitejs/vite-plugin-react-swc#14]
When using commonjs imports

```js
const react = require('@vitejs/plugin-react-swc');
```

We get `TypeError: react is not a function`. It works with esm imports, but I thought this was worth bringing up.

Example reproduction:

https://stackblitz.com/edit/vitejs-vite-tcrxby?file=vite.config.js

**Comment by ArnaudBarre** [comment]
There is not SWC bindings available for Stackblitz yet, so with ESM if fails just after. That's strange though, there is probably an issue with default export. Thanks for reporting!

**Comment by ArnaudBarre** [comment]
So yeah basically this a classic interop issue, which is why we should move away from default export (or cjs, but one is simpler than the other).

I can patch esbuild output for the cjs output, but before doing that I want to know if it will be possible to support this directly in esbuild: https://github.com/evanw/esbuild/issues/2733

In the meantime you can change your export to `require('@vitejs/plugin-react-swc').default`
