### ISSUE TITLE
"React refresh runtime was loaded twice." after HTTP 304

### ISSUE THREAD

**Issue by Poyoman39** [vitejs/vite-plugin-react-swc#180]
I'm not sure it is a Vite error or a React one. Anyway i am using vite-plugin-react-swc on my project, and i get this error :

When i try to acceed to my react app with an "auto login url" i get a 304 (which is normal) then my react page does not load correctly (in production and in development mode)

To reproduce this, you can try to go to http://foo:bar@localhost:3000/ with google chrome or chromium (I don't get the problem when using firefox). You will get a blank page and console will tell you "React refresh runtime was loaded twice."

**Comment by ArnaudBarre** [comment]
This is an interesting bug from Chromium. I have simplified it to the minimum and submitted to their bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1507675
You can follow the issue theere.

In the meantime you can:
- avoid chrome when starting the app with user info in the url.
- [patch](https://www.npmjs.com/package/patch-package) the module so that it's remove the safe guard (this can lead to broken HMR to load the module twice, but in this specific case it's strangely works)
- use a small plugin to proxy the react-refresh import so that it doesn't trigger the chrome bug

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";

const rrProxy = "/@react-refresh-proxy";
export default defineConfig({
  plugins: [
    react(),
    {
      name: "fix-chrome-bug",
      transformIndexHtml: (html) => html.replace("/@react-refresh", rrProxy),
      resolveId: (id) => (id === rrProxy ? id : undefined),
      load: (id) => (id === rrProxy ? `export * from "/@react-refresh"` : undefined),
    },
  ],
});
```
