### ISSUE TITLE
HMR failed, but not reload full page automatically, and causes the page to go blank.

### ISSUE THREAD

**Issue by Innei** [vitejs/vite-plugin-react-swc#187]
Refer: https://x.com/__oQuery/status/1742862717562794490?s=20

Repo: https://github.com/Innei/vite-edgecase-hmr-whitepage

Demo: https://twitter.com/i/status/1742862717562794490

**Comment by ArnaudBarre** [comment]
Thanks for the report and sorry I didn't have time to look at it before. The issue is that the router doesn't support an update of the router prop. I proposed a fix: https://github.com/TanStack/router/pull/1054

In the meantime you can go around it with this key hack: https://github.com/TanStack/router/issues/902#issuecomment-1898311293

**Comment by ArnaudBarre** [comment]
The bug fixed was released https://github.com/TanStack/router/releases/tag/v1.8.4 :)

**Comment by JoeSlain** [comment]
Hi there, I used the bun template `bun create @tanstack/router` but running dev always prints blank pages
Running preview works tho
