### ISSUE TITLE
`@swc/plugin-styled-components`: `displayName` not showing when importing from `.js` file in React

### ISSUE THREAD

**Issue by rakleed** [vitejs/vite-plugin-react-swc#226]
## Description of problem

`displayName` is not displayed when importing styled-component from `.js` file in React, although there is no such problem when importing from `.jsx`.

---
I initially created an issue in the `@swc/plugin-styled-components` repository (https://github.com/swc-project/plugins/issues/335), but the author responded with the following:
> I think this is a bug of `vite-plugin-swc`. SWC transforms has nothing to do with file extensions

## Steps to reproduce

1. `git clone https://github.com/rakleed/styled-test-swc`
2. `npm install && npm run dev`
3. Open DevTools and look at div with text `styled-test-swc`

However, there is no such problem with `babel-plugin-styled-components`. To check this, you can comment out lines 1 and 7 and uncomment lines 2 and 8 in the `vite.config.js` file.

## Screenshots

<details><summary>Screenshot with @swc/plugin-styled-components:</summary>

![CleanShot 2024-08-03 at 03 08 24](https://github.com/user-attachments/assets/db2ba6e8-fe9f-48f0-b79e-3d30f252f558)

</details>

<details><summary>Screenshot with babel-plugin-styled-components:</summary>

![CleanShot 2024-08-03 at 03 08 51](https://github.com/user-attachments/assets/15d91e8e-6d94-4c51-bdff-e2b3226bd9d0)

</details>

## Minimal reproduction

https://github.com/rakleed/styled-test-swc

**Comment by ArnaudBarre** [comment]
This is by design: https://github.com/vitejs/vite-plugin-react-swc#:~:text=JS%20files%20are%20not%20transformed

We discouraged using JS extension for JSX. Here this is obviously a edge case because this is actually valid JS.
I think using `.jsx` for this case is fine, but my recommendation would be to move to `.ts`.

You can also use parserConfig option, but this is not recommended and you need to be sure to exclude node_modules
